const { required } = require("../routes/auth");

require("./admins");
require("./vehicles");
require("./drivers");
require("./products");
require("./users");
require("./users_locations");
require("./collectionpoints");
require("./suburbs");
require("./boxes");
require("./sensors");
require("./addresses");
require("./settings");
require("./excessstock");
require("./stocks");
require("./tmp_bookings");
require("./tmp_payments");
require("./bookings");
require("./notifications");
require("./banners");
require("./coupons");
require("./payments");
require("./stock_requests");
require("./driver_logs");
require("./driver_alerts")
require("./tmp_credit")
require("./credits")
require("./stock_transfers")
require("./cp_stocks")
require("./job_notifications")
require("./driver_notifications")
require("./cp_sales")
require("./ratings")
require("./scheduled_stock_limits")
require("./stock_request_cp")
require("./about_us")
require("./terms_conditions")
require("./privacy_policies")
require("./temp_log")
require("./booking_slots")
require("./transactions")
require('./banners_userapp')
require('./companies')
require('./temp_companies')